a=str(input())
if(a=="Sunday"):
  print("yes")
elif(a=="Saturday"):
  print("yes")  
elif(a=="Monday"):
  print("no")   
elif(a=="Tuesday"):
  print("no")
elif(a=="Wednesday"):
  print("no")
elif(a=="Thursday"):
  print("no")   
elif(a=="Friday"):
  print("no")   
